objects : [ 'sports ball','teddy bear', 'remote','bottle', 'cell phone', 'fork', 'tie', 'pen', 'umbrella', 'suitcase', 'banana', 'apple', 'laptop', 'mouse','vase', 'scizors','book',
            'clock','hairdrier', 'toothbrush', 'pizza', 'donut','cake', 'wine glass', 'bear', 'orange', 'bowl','knife','cup','sandwich']
